### ISSUE TITLE
Using yun shield with cylonjs.

### ISSUE THREAD

**Issue by manu354** [hybridgroup/cylon#323]
Hi, 

I want to use the yun shield with the Arduino uno or Arduino mega ( I have both) and I was wondering if it would work just like an Arduino yun or with nodejs at all? 

Here's the stack overflow question: 
http://stackoverflow.com/q/34393144/5210362

**Comment by deadprogram** [comment]
Hello, @manu354 

I have not tried this option, and do not have a Yun shield, although I do have a Yun. Probably you could follow the instructions we have for Yun? http://cylonjs.com/documentation/platforms/yun/ 

However, since the Yun shield does not appear to have an SD card, you will need to use a USB drive to transfer the files. In any case, please let us know how it goes if you decide to give it a try.

**Comment by manu354** [comment]
The yun shield 2.3 has an mini sd  slot.

**Comment by deadprogram** [comment]
That being the case it *should* work. Please let us know how it works out, if you give it a try.

**Comment by manu354** [comment]
Hey, I just got it working with an arduino leonardo and yun shield. It works! It will work with any yun shield that has an sd card. Nothing to tweak, works exactly like an arduino yun.
